name: pizza_app
description: A new Flutter pizza ordering app.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.1
  geolocator: ^11.0.0
  uuid: ^4.3.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/mala_shan.png
    - assets/images/dan_pauk.png
    - assets/images/cold_drinks.png
    - assets/images/pizza.png
    - assets/images/dessert.png
    - assets/images/promo.png
    - assets/images/promo_burmese.png
    - assets/images/Ohn_No_Khao_Swè.png
    - assets/images/mala_beef.png
    - assets/images/dan_pauk_curry.png
    - assets/images/iced_tea.png
    - assets/images/placeholder.png