name: Naraon
description: A new Flutter pizza ordering app.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.1
  geolocator: ^11.0.0
  uuid: ^4.3.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/mala_shan.png
    - assets/images/dan_pauk.png
    - assets/images/cold_drinks.png
    - assets/images/pizza.png
    - assets/images/dessert.png
    - assets/images/promo.png
    - assets/images/promo_burmese.png
    - assets/images/Ohn_No_Khao_Swè.png
    - assets/images/mala_beef.png
    - assets/images/dan_pauk_curry.png
    - assets/images/iced_tea.png
    - assets/images/placeholder.png
    - assets/images/burger.png
    - assets/images/noodles.png
    - assets/images/mala.png
    - assets/images/ice_cream.png
    - assets/images/tea.png
    - assets/images/berry_cake.png
    - assets/images/choco_cake.png
    - assets/images/sweet_treats.png
    - assets/images/fried_chicken.png
    - assets/images/fried_chicken2.png
    - assets/images/fried_potato.png
    - assets/images/summer_drink.png
    - assets/images/orange.png
    - assets/images/mala_beef2.png
    - assets/images/mala_beef3.png
    - assets/images/mala_beef4.png
    - assets/images/dan_pauk2.png
    - assets/images/dan_pauk3.png
    - assets/images/berry_drink.png
    - assets/images/gradeful_drink.png
    - assets/images/kp.png
    - assets/images/kp2.png
    - assets/images/krc.png
    - assets/images/krc2.png
    - assets/images/login_bg.png
    - assets/images/Pizza Margherita.png
    - assets/images/Spaghetti Carbonara.png
    - assets/images/Caesar Salad.png
    - assets/images/Spicy_Mala.png
    - assets/images/mala_soup.png
    - assets/images/mutton_biryani.png
    - assets/images/veg_biryani.png
    - assets/images/lemonade.png
    - assets/images/cold_coffee.png
    - assets/images/margherita.png
    - assets/images/bbq_chicken.png
    - assets/images/ice_creams.png
    - assets/images/fruit_tart.png